#+title: 見上げる. 

Bad pun.

Work in progress.

* Purpose

Consolidate a bunch of organic scripts for looking up and processing Japanese terms.

Do this in a way that is flexible to the user environment including what, if any, remote services may be used.

* Architecture

miegeru is comprised of three layers

- commands :: ~miageru <command>~ command line interface
- methods :: an set of named operations
- tools :: a supplier of one or more methods

A tool object is a named, configured instance of a class in the =miageru.tools=
namespace.  A tool class provides one or more methods as class functions.  Every
tool class has a tool instance named by its Python module.  Variant tool
instances are defined by the configuration file.

Multiple tools classes may provide the same method.  For example, the ~gtts~ tool
provides access to Google text-to-speech service by providing the ~tts~ method.
The ~jtalk~ tool also provides the ~tts~ method by running the local ~open_jtalk~
program (possibly with voices provided by miageru).

The motivation for this abstraction is to allow operations to be defined with a
common CLI and API while allowing flexibility in how the user may satisfy
dependencies.  

A side-effect of this structuring is that the ~miageru~ command line program can
load relatively quickly (for Python) as it avoids the cost of importing modules
it does not use (minimal ~python~: 15ms, ~miageru~ with no arguments: 50 ms).  The
~miageru.methods.Method~ class provides a simple interface to resolve methods via
the user configuration and hide the complexity that comes with this flexibility.

* TODO

- [ ] yad ui to show dict text with ~[say (jtalk)] [say (gtts)]~ buttons
- [X] a ~read~ command giving the kanji to hiragana text 
- [X] introduce ability to show window of text ++(zenity and kitty tools)++ used yad
- [X] configuration
- [ ] introduce anki card generation and sending to anki-connect
- [ ] ...
